# Config MinIO
spark.hadoop.fs.s3a.impl                   org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.path.style.access      true
spark.hadoop.hadoop.security.authentication=simple
spark.hadoop.fs.s3a.endpoint               http://minio:9000
spark.sql.warehouse.dir                    s3a://warehouse/

# for test only
spark.hadoop.fs.s3a.access.key   spark
spark.hadoop.fs.s3a.secret.key   sparkconnection123
# chemin du metastore (table schema and else) `derby` db par défaut de Hive/ il faudra une architecture de production avec RDBS (PostgreSQL, MySQL, etc.)
spark.hadoop.javax.jdo.option.ConnectionURL=jdbc:derby:/data/metastore_db;create=true

# Config Iceberg
spark.jars=/opt/bitnami/spark/jars/iceberg-spark3-runtime.jar
spark.driver.extraClassPath=/opt/bitnami/spark/jars/iceberg-spark3-runtime.jar
spark.executor.extraClassPath=/opt/bitnami/spark/jars/iceberg-spark3-runtime.jar
#spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions # visualize iceberg tables
spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.spark_catalog.type=hadoop
spark.sql.catalog.spark_catalog.warehouse=s3a://warehouse/
spark.sql.catalog.local                    org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.local.type               hadoop
spark.sql.catalog.local.warehouse          s3a://warehouse/

# Ivy error debugging
spark.jars.ivy=/tmp/.ivy
