
dbt_project:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: default
      host: localhost
      port: 10000
      user: "{{ env_var('USER') }}"
      connect_retries: 5
      connect_timeout: 60
      retries: 3
      http_path: ""
      session_properties:
        spark.sql.catalog.spark_catalog: org.apache.iceberg.spark.SparkCatalog
        spark.sql.catalog.spark_catalog.type: hadoop
        spark.sql.catalog.spark_catalog.warehouse: s3a://warehouse/
        spark.hadoop.fs.s3a.endpoint: http://minio:9000
        spark.hadoop.fs.s3a.path.style.access: "true"
        spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
        spark.hadoop.fs.s3a.access.key: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        spark.hadoop.fs.s3a.secret.key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
